
    import hilog from '@ohos.hilog';
    import AbilityDelegatorRegistry from '@ohos.app.ability.abilityDelegatorRegistry'

    import {Hypium} from '@ohos/hypium'
    import testsuite from '../../../src/test/List.test'

    const global: object = new Function("return this")();
    const savePath = '__savePath__';
    const readPath = '__readPath__';
    const testMode: string = '__testMode__';
    global[savePath] = "/Users/yaoshining/DevEcoStudioProjects/VidAll_TV/entry/.test/default/intermediates/test/coverage_data/js_coverage.json";
    global[readPath] = "/Users/yaoshining/DevEcoStudioProjects/VidAll_TV/entry/.test/default/intermediates/test/coverage_data/js_coverage.json"
    global[testMode] = 'unitTest';

    @Entry
    @Component
    struct Index1 {
      aboutToAppear() {
        console.info('[LOCAL_TEST] START')
        let abilityDelegator: AbilityDelegatorRegistry.AbilityDelegator;
        abilityDelegator = AbilityDelegatorRegistry.getAbilityDelegator();
        let abilityDelegatorArguments: AbilityDelegatorRegistry.AbilityDelegatorArgs;
        abilityDelegatorArguments = AbilityDelegatorRegistry.getArguments();
        abilityDelegatorArguments.bundleName = "com.yao.vidalltv";
        abilityDelegatorArguments.parameters = {
          "-b": "com.yao.vidalltv",
          "-m": "entry",
          "-s class": "",
          "-s timeout": "15000",
          "-s coverage": "true"
        };
        abilityDelegatorArguments.testCaseNames = ""
        console.info("[LOCAL_TEST] " + abilityDelegatorArguments);
        Hypium.hypiumTest(abilityDelegator, abilityDelegatorArguments, testsuite)
        console.info('[LOCAL_TEST] END')
      }
    
      @State
      message: string = 'Hello World'
    
      
  build() {
    Row() {
      Column() {
        Text(this.message)
          .fontSize(50)
          .fontWeight(FontWeight.Bold)
        Button() {
          Text('next page')
            .fontSize(20)
            .fontWeight(FontWeight.Bold)
        }
        .type(ButtonType.Capsule)
        .margin({
          top: 20
        })
        .backgroundColor('#0D9FFB')
        .width('35%')
        .height('5%')
        .onClick(() => {
        })
      }
      .width('100%')
    }
    .height('100%')
  }

    }