@Builder
export function SmbIcon() {
  Image($r('app.media.windows'))
    .width(30)
    .height(30)
    .objectFit(ImageFit.Contain)
}

@Builder
export function WebdavIcon() {
  Image($r('app.media.global_folder'))
    .width(30)
    .height(30)
    .objectFit(ImageFit.Contain)
}

@Builder
export function AliyunIcon() {
  Image($r('app.media.aliyun_drive'))
    .width(30)
    .height(30)
    .objectFit(ImageFit.Contain)
}

@Builder
export function Cloud139Icon() {
  Image($r('app.media.netdisk_139'))
    .width(30)
    .height(30)
    .objectFit(ImageFit.Contain)
}

@Builder
export function BaiduIcon() {
  Image($r('app.media.baidu_netdisk'))
    .width(30)
    .height(30)
    .objectFit(ImageFit.Contain)
}

@Builder
export function Cloud123Icon() {
  Image($r('app.media.drive_123'))
    .width(30)
    .height(30)
    .objectFit(ImageFit.Contain)
}

@Builder
export function Cloud115Icon() {
  Image($r('app.media.netdisk_115'))
    .width(30)
    .height(30)
    .objectFit(ImageFit.Contain)
}

@Builder
export function OtherIcon() {
  Image($r('app.media.cloud_drive'))
    .width(30)
    .height(30)
    .objectFit(ImageFit.Contain)
}

