export default class SettingType {
  static HOME = "Home"  // 总设置入口
  static FILE_SOURCE = "fileSource"  // 文件源列表
  static VIDEO_SERVER = "videoServer"  // 影视服务器
  static RESOURCE_LIBRARY = "resourceLibrary" // 资源库
  static ADD_FILE_SOURCE = "addFileSource" // 添加文件源
  static WEBDAV_CONFIG = "webdavConfig" // WebDAV 配置
  static SMB_CONFIG = "smbConfig" // SMB 配置
  static DIRECTORY_SELECTOR = "directorySelector" // WebDAV 文件夹选择器
  static SMB_DIRECTORY_SELECTOR = "smbDirectorySelector" // SMB 文件夹选择器（WebDAV）
  static SMB_DIRECTORY_SELECTOR = "smbDirectorySelector" // SMB 文件夹选择器
}
